#!/usr/bin/env python3
"""
Script to populate the local database with test player and WITB data
"""

import asyncio
import os
import sys

from sqlalchemy.exc import IntegrityError

# Add current directory to path to import models
sys.path.append(os.path.dirname(__file__))

import models
from database import SessionLocal

# Test data for 25+ professional golfers
PLAYERS_DATA = [
    # Major Championship Winners & Top Players
    {
        "name": "Scottie Scheffler",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Fujikura Ventus Black 6X",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Fujikura Ventus Blue 7X",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "22°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "25°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "28°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "32°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "36°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "40°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "44°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "Sand Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "56°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Lob Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "60°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Special Select Newport 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Rory McIlroy",
        "country": "Northern Ireland",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Fujikura Ventus Black 6X",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Mitsubishi Diamana D+ 80 X",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "TaylorMade",
                "model": "Spider Tour X",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Jon Rahm",
        "country": "Spain",
        "tour": "LIV Golf",
        "witb": [
            {
                "category": "Driver",
                "brand": "Callaway",
                "model": "Paradym",
                "loft": "9°",
                "shaft": "Project X HZRDUS Smoke Green RDX 70 6.5",
            },
            {
                "category": "3-Wood",
                "brand": "Callaway",
                "model": "Paradym",
                "loft": "15°",
                "shaft": "Project X HZRDUS Smoke Green RDX 80 6.5",
            },
            {
                "category": "4-Iron",
                "brand": "Callaway",
                "model": "Apex MB",
                "loft": "22°",
                "shaft": "KBS Tour V 125 X",
            },
            {
                "category": "5-Iron",
                "brand": "Callaway",
                "model": "Apex MB",
                "loft": "25°",
                "shaft": "KBS Tour V 125 X",
            },
            {
                "category": "6-Iron",
                "brand": "Callaway",
                "model": "Apex MB",
                "loft": "28°",
                "shaft": "KBS Tour V 125 X",
            },
            {
                "category": "7-Iron",
                "brand": "Callaway",
                "model": "Apex MB",
                "loft": "32°",
                "shaft": "KBS Tour V 125 X",
            },
            {
                "category": "8-Iron",
                "brand": "Callaway",
                "model": "Apex MB",
                "loft": "36°",
                "shaft": "KBS Tour V 125 X",
            },
            {
                "category": "9-Iron",
                "brand": "Callaway",
                "model": "Apex MB",
                "loft": "40°",
                "shaft": "KBS Tour V 125 X",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Callaway",
                "model": "Apex MB",
                "loft": "44°",
                "shaft": "KBS Tour V 125 X",
            },
            {
                "category": "Gap Wedge",
                "brand": "Callaway",
                "model": "Jaws MD5",
                "loft": "50°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Sand Wedge",
                "brand": "Callaway",
                "model": "Jaws MD5",
                "loft": "56°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Lob Wedge",
                "brand": "Callaway",
                "model": "Jaws MD5",
                "loft": "60°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Putter",
                "brand": "Odyssey",
                "model": "White Hot OG #7",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Viktor Hovland",
        "country": "Norway",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "PING",
                "model": "G430 LST",
                "loft": "9°",
                "shaft": "Graphite Design Tour AD IZ 7X",
            },
            {
                "category": "3-Wood",
                "brand": "PING",
                "model": "G430",
                "loft": "14.5°",
                "shaft": "Graphite Design Tour AD IZ 8X",
            },
            {
                "category": "4-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "PING",
                "model": "Anser 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Xander Schauffele",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Callaway",
                "model": "Paradym",
                "loft": "9°",
                "shaft": "Project X HZRDUS Smoke Green RDX 70 6.0",
            },
            {
                "category": "3-Wood",
                "brand": "Callaway",
                "model": "Paradym",
                "loft": "15°",
                "shaft": "Project X HZRDUS Smoke Green RDX 80 6.0",
            },
            {
                "category": "Driving Iron",
                "brand": "Callaway",
                "model": "Apex UT",
                "loft": "18°",
                "shaft": "Project X HZRDUS Smoke Green RDX 105 6.5",
            },
            {
                "category": "4-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue S400",
            },
            {
                "category": "5-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue S400",
            },
            {
                "category": "6-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue S400",
            },
            {
                "category": "7-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue S400",
            },
            {
                "category": "8-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue S400",
            },
            {
                "category": "9-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue S400",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue S400",
            },
            {
                "category": "Gap Wedge",
                "brand": "Callaway",
                "model": "Jaws MD5",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Callaway",
                "model": "Jaws MD5",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Callaway",
                "model": "Jaws MD5",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Odyssey",
                "model": "White Hot OG #1WS",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Keegan Bradley",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Srixon",
                "model": "ZX5",
                "loft": "9°",
                "shaft": "Fujikura Ventus Blue 6X",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "Qi10 HL",
                "loft": "16.5°",
                "shaft": "Aldila Rogue White 130 MSI 70 TX",
            },
            {
                "category": "5-Wood",
                "brand": "TaylorMade",
                "model": "Qi10 HL",
                "loft": "19°",
                "shaft": "Aldila Rogue White 130 MSI 70 TX",
            },
            {
                "category": "4-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Wedges",
                "brand": "Cleveland",
                "model": "RTZ Tour Rack",
                "loft": "52-10 Mid, 56-10 Mid, 58-06 LOW",
                "shaft": "True Temper Dynamic Gold Tour Issue S400",
            },
            {
                "category": "Putter",
                "brand": "Odyssey",
                "model": "White Hot OG #7",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Patrick Cantlay",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "9°",
                "shaft": "Graphite Design Tour AD IZ 7X",
            },
            {
                "category": "3-Wood",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "15°",
                "shaft": "Graphite Design Tour AD IZ 8X",
            },
            {
                "category": "Utility",
                "brand": "Titleist",
                "model": "U505",
                "loft": "18°",
                "shaft": "Project X HZRDUS Smoke Green RDX 105 6.5",
            },
            {
                "category": "4-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Titleist",
                "model": "T100",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Special Select Newport 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Collin Morikawa",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Mitsubishi Diamana D+ Limited 70 TX",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Mitsubishi Diamana D+ Limited 80 TX",
            },
            {
                "category": "Driving Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "18°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "TaylorMade",
                "model": "Spider Tour X",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Justin Thomas",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "9.5°",
                "shaft": "Graphite Design Tour AD IZ 7X",
            },
            {
                "category": "3-Wood",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "15°",
                "shaft": "Graphite Design Tour AD IZ 8X",
            },
            {
                "category": "Utility",
                "brand": "Titleist",
                "model": "U505",
                "loft": "18°",
                "shaft": "Project X HZRDUS Smoke Green RDX 105 6.5",
            },
            {
                "category": "4-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Titleist",
                "model": "T100",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Special Select Newport 2.5",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Hideki Matsuyama",
        "country": "Japan",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Srixon",
                "model": "ZX5",
                "loft": "9.5°",
                "shaft": "Graphite Design Tour AD IZ 7X",
            },
            {
                "category": "3-Wood",
                "brand": "Srixon",
                "model": "ZX",
                "loft": "15°",
                "shaft": "Graphite Design Tour AD IZ 8X",
            },
            {
                "category": "5-Wood",
                "brand": "Srixon",
                "model": "ZX",
                "loft": "18°",
                "shaft": "Graphite Design Tour AD IZ 9X",
            },
            {
                "category": "4-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Cleveland",
                "model": "RTX ZipCore",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Cleveland",
                "model": "RTX ZipCore",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Cleveland",
                "model": "RTX ZipCore",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Special Select Newport 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Max Homa",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Fujikura Ventus Blue 6X",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Fujikura Ventus Blue 7X",
            },
            {
                "category": "5-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "19°",
                "shaft": "Fujikura Ventus Blue 8X",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "22°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "25°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "28°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "32°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "36°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "40°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "44°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "Gap Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "50°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Sand Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "56°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Lob Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "60°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Putter",
                "brand": "Ping",
                "model": "Anser 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Jordan Spieth",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "9.5°",
                "shaft": "Fujikura Ventus Black 6X",
            },
            {
                "category": "3-Wood",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "15°",
                "shaft": "Fujikura Ventus Black 7X",
            },
            {
                "category": "Utility",
                "brand": "Titleist",
                "model": "U505",
                "loft": "21°",
                "shaft": "Project X HZRDUS Smoke Green RDX 105 6.5",
            },
            {
                "category": "4-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "24°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "27°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "30°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "34°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "38°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "42°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Titleist",
                "model": "T100",
                "loft": "46°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "52°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Circle T 009",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Tony Finau",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "PING",
                "model": "G430 LST",
                "loft": "9°",
                "shaft": "Mitsubishi Diamana D+ Limited 70 TX",
            },
            {
                "category": "3-Wood",
                "brand": "PING",
                "model": "G430",
                "loft": "14.5°",
                "shaft": "Mitsubishi Diamana D+ Limited 80 TX",
            },
            {
                "category": "5-Wood",
                "brand": "PING",
                "model": "G430",
                "loft": "17.5°",
                "shaft": "Mitsubishi Diamana D+ Limited 90 TX",
            },
            {
                "category": "4-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "PING",
                "model": "Blueprint",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "PING",
                "model": "Anser 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Cameron Smith",
        "country": "Australia",
        "tour": "LIV Golf",
        "witb": [
            {
                "category": "Driver",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "9°",
                "shaft": "Graphite Design Tour AD IZ 7X",
            },
            {
                "category": "3-Wood",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "15°",
                "shaft": "Graphite Design Tour AD IZ 8X",
            },
            {
                "category": "Utility",
                "brand": "Titleist",
                "model": "U505",
                "loft": "18°",
                "shaft": "Project X HZRDUS Smoke Green RDX 105 6.5",
            },
            {
                "category": "4-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Titleist",
                "model": "T100",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Special Select Newport 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Will Zalatoris",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Fujikura Ventus Black 6X",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Fujikura Ventus Black 7X",
            },
            {
                "category": "Driving Iron",
                "brand": "TaylorMade",
                "model": "P790 UDI",
                "loft": "18°",
                "shaft": "KBS Tour Prototype 130 X",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "22°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "25°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "28°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "32°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "36°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "40°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "44°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "Gap Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "50°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Sand Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "56°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Lob Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "60°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Putter",
                "brand": "TaylorMade",
                "model": "Spider Tour X",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Tommy Fleetwood",
        "country": "England",
        "tour": "DP World Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Fujikura Ventus Blue 6X",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Fujikura Ventus Blue 7X",
            },
            {
                "category": "5-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "19°",
                "shaft": "Fujikura Ventus Blue 8X",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Odyssey",
                "model": "White Hot OG #7",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Rickie Fowler",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Aldila Rogue White 130 MSI 70 TX",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Aldila Rogue White 130 MSI 80 TX",
            },
            {
                "category": "5-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "19°",
                "shaft": "Aldila Rogue White 130 MSI 90 TX",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Special Select Newport 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Jason Day",
        "country": "Australia",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Fujikura Ventus Black 6X",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Fujikura Ventus Black 7X",
            },
            {
                "category": "5-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "19°",
                "shaft": "Fujikura Ventus Black 8X",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "TaylorMade",
                "model": "Spider Tour X",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Russell Henley",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Callaway",
                "model": "Paradym",
                "loft": "9°",
                "shaft": "Project X HZRDUS Smoke Green RDX 70 6.5",
            },
            {
                "category": "3-Wood",
                "brand": "Callaway",
                "model": "Paradym",
                "loft": "15°",
                "shaft": "Project X HZRDUS Smoke Green RDX 80 6.5",
            },
            {
                "category": "Utility",
                "brand": "Callaway",
                "model": "Apex UT",
                "loft": "18°",
                "shaft": "Project X HZRDUS Smoke Green RDX 105 6.5",
            },
            {
                "category": "4-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Callaway",
                "model": "Apex Pro",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Callaway",
                "model": "Jaws MD5",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Callaway",
                "model": "Jaws MD5",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Callaway",
                "model": "Jaws MD5",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Odyssey",
                "model": "White Hot OG #1WS",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Adam Scott",
        "country": "Australia",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "9.5°",
                "shaft": "Graphite Design Tour AD IZ 7X",
            },
            {
                "category": "3-Wood",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "15°",
                "shaft": "Graphite Design Tour AD IZ 8X",
            },
            {
                "category": "Utility",
                "brand": "Titleist",
                "model": "U505",
                "loft": "18°",
                "shaft": "Project X HZRDUS Smoke Green RDX 105 6.5",
            },
            {
                "category": "4-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Titleist",
                "model": "T100",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Special Select Newport 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Sam Burns",
        "country": "USA",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Fujikura Ventus Blue 6X",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Fujikura Ventus Blue 7X",
            },
            {
                "category": "5-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "19°",
                "shaft": "Fujikura Ventus Blue 8X",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "22°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "25°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "28°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "32°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "36°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "40°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P7MC",
                "loft": "44°",
                "shaft": "KBS Tour 130 X",
            },
            {
                "category": "Gap Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "50°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Sand Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "56°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Lob Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "60°",
                "shaft": "KBS Hi-Rev 2.0",
            },
            {
                "category": "Putter",
                "brand": "TaylorMade",
                "model": "Spider Tour X",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Bryson DeChambeau",
        "country": "USA",
        "tour": "LIV Golf",
        "witb": [
            {
                "category": "Driver",
                "brand": "Cobra",
                "model": "King LTDx LS",
                "loft": "7.5°",
                "shaft": "LA Golf AXS Blue 80 X",
            },
            {
                "category": "3-Wood",
                "brand": "Cobra",
                "model": "King LTDx",
                "loft": "13.5°",
                "shaft": "LA Golf AXS Blue 90 X",
            },
            {
                "category": "5-Wood",
                "brand": "Cobra",
                "model": "King LTDx",
                "loft": "17.5°",
                "shaft": "LA Golf AXS Blue 100 X",
            },
            {
                "category": "4-Iron",
                "brand": "Cobra",
                "model": "King Tour",
                "loft": "20°",
                "shaft": "LA Golf AXS Blue 120 X",
            },
            {
                "category": "5-Iron",
                "brand": "Cobra",
                "model": "King Tour",
                "loft": "23°",
                "shaft": "LA Golf AXS Blue 120 X",
            },
            {
                "category": "6-Iron",
                "brand": "Cobra",
                "model": "King Tour",
                "loft": "26°",
                "shaft": "LA Golf AXS Blue 120 X",
            },
            {
                "category": "7-Iron",
                "brand": "Cobra",
                "model": "King Tour",
                "loft": "30°",
                "shaft": "LA Golf AXS Blue 120 X",
            },
            {
                "category": "8-Iron",
                "brand": "Cobra",
                "model": "King Tour",
                "loft": "34°",
                "shaft": "LA Golf AXS Blue 120 X",
            },
            {
                "category": "9-Iron",
                "brand": "Cobra",
                "model": "King Tour",
                "loft": "38°",
                "shaft": "LA Golf AXS Blue 120 X",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Cobra",
                "model": "King Tour",
                "loft": "42°",
                "shaft": "LA Golf AXS Blue 120 X",
            },
            {
                "category": "Gap Wedge",
                "brand": "Cobra",
                "model": "King MIM",
                "loft": "48°",
                "shaft": "LA Golf AXS Blue 130 X",
            },
            {
                "category": "Sand Wedge",
                "brand": "Cobra",
                "model": "King MIM",
                "loft": "56°",
                "shaft": "LA Golf AXS Blue 130 X",
            },
            {
                "category": "Lob Wedge",
                "brand": "Cobra",
                "model": "King MIM",
                "loft": "60°",
                "shaft": "LA Golf AXS Blue 130 X",
            },
            {
                "category": "Putter",
                "brand": "Sik Golf",
                "model": "Pro C Series",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Dustin Johnson",
        "country": "USA",
        "tour": "LIV Golf",
        "witb": [
            {
                "category": "Driver",
                "brand": "TaylorMade",
                "model": "Qi10",
                "loft": "9°",
                "shaft": "Fujikura Ventus Black 7X",
            },
            {
                "category": "3-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "15°",
                "shaft": "Fujikura Ventus Black 8X",
            },
            {
                "category": "5-Wood",
                "brand": "TaylorMade",
                "model": "SIM2",
                "loft": "19°",
                "shaft": "Fujikura Ventus Black 9X",
            },
            {
                "category": "4-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "TaylorMade",
                "model": "P730",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "TaylorMade",
                "model": "MG4",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "TaylorMade",
                "model": "Spider Tour Black",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Brooks Koepka",
        "country": "USA",
        "tour": "LIV Golf",
        "witb": [
            {
                "category": "Driver",
                "brand": "Srixon",
                "model": "ZX5",
                "loft": "9°",
                "shaft": "Graphite Design Tour AD IZ 7X",
            },
            {
                "category": "3-Wood",
                "brand": "Srixon",
                "model": "ZX",
                "loft": "15°",
                "shaft": "Graphite Design Tour AD IZ 8X",
            },
            {
                "category": "5-Wood",
                "brand": "Srixon",
                "model": "ZX",
                "loft": "18°",
                "shaft": "Graphite Design Tour AD IZ 9X",
            },
            {
                "category": "4-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Cleveland",
                "model": "RTX ZipCore",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Cleveland",
                "model": "RTX ZipCore",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Cleveland",
                "model": "RTX ZipCore",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Special Select Newport 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Matt Fitzpatrick",
        "country": "England",
        "tour": "PGA Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "9°",
                "shaft": "Graphite Design Tour AD IZ 7X",
            },
            {
                "category": "3-Wood",
                "brand": "Titleist",
                "model": "TSR3",
                "loft": "15°",
                "shaft": "Graphite Design Tour AD IZ 8X",
            },
            {
                "category": "Utility",
                "brand": "Titleist",
                "model": "U505",
                "loft": "18°",
                "shaft": "Project X HZRDUS Smoke Green RDX 105 6.5",
            },
            {
                "category": "4-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Titleist",
                "model": "T100",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Titleist",
                "model": "T100",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Titleist",
                "model": "Vokey SM9",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Scotty Cameron",
                "model": "Special Select Newport 2",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
    {
        "name": "Shane Lowry",
        "country": "Ireland",
        "tour": "DP World Tour",
        "witb": [
            {
                "category": "Driver",
                "brand": "Srixon",
                "model": "ZX5",
                "loft": "9°",
                "shaft": "Graphite Design Tour AD IZ 7X",
            },
            {
                "category": "3-Wood",
                "brand": "Srixon",
                "model": "ZX",
                "loft": "15°",
                "shaft": "Graphite Design Tour AD IZ 8X",
            },
            {
                "category": "5-Wood",
                "brand": "Srixon",
                "model": "ZX",
                "loft": "18°",
                "shaft": "Graphite Design Tour AD IZ 9X",
            },
            {
                "category": "4-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "22°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "5-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "25°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "6-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "28°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "7-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "32°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "8-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "36°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "9-Iron",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "40°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Pitching Wedge",
                "brand": "Srixon",
                "model": "ZX7",
                "loft": "44°",
                "shaft": "True Temper Dynamic Gold Tour Issue X100",
            },
            {
                "category": "Gap Wedge",
                "brand": "Cleveland",
                "model": "RTX ZipCore",
                "loft": "50°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Sand Wedge",
                "brand": "Cleveland",
                "model": "RTX ZipCore",
                "loft": "56°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Lob Wedge",
                "brand": "Cleveland",
                "model": "RTX ZipCore",
                "loft": "60°",
                "shaft": "True Temper Dynamic Gold",
            },
            {
                "category": "Putter",
                "brand": "Odyssey",
                "model": "White Hot OG #7",
                "loft": "3°",
                "shaft": "Steel",
            },
        ],
    },
]


async def populate_database():
    """Populate the database with test player and WITB data"""
    print("Starting database population...")

    async with SessionLocal() as session:
        try:
            for player_data in PLAYERS_DATA:
                print(f"Adding player: {player_data['name']}")

                # Create player
                player = models.Player(
                    name=player_data["name"],
                    country=player_data["country"],
                    tour=player_data["tour"],
                    photo_url=None,  # We'll add photos later if needed
                )

                session.add(player)
                await session.flush()  # Get the player ID

                # Add WITB items
                witb_count = 0
                for witb_item in player_data["witb"]:
                    item = models.WITBItem(
                        player_id=player.id,
                        category=witb_item["category"],
                        brand=witb_item["brand"],
                        model=witb_item["model"],
                        loft=witb_item.get("loft"),
                        shaft=witb_item.get("shaft"),
                    )
                    session.add(item)
                    witb_count += 1

                print(f"  Added {witb_count} WITB items for {player_data['name']}")

            await session.commit()
            print(
                f"\n✅ Successfully added {len(PLAYERS_DATA)} players with their WITB data!"
            )

        except IntegrityError as e:
            await session.rollback()
            print(f"❌ Database integrity error: {e}")
        except Exception as e:
            await session.rollback()
            print(f"❌ Error populating database: {e}")


async def main():
    """Main function to run the population script"""
    await populate_database()


if __name__ == "__main__":
    asyncio.run(main())
